version: "3"

services:
  app:
    build: .
    container_name: personal_website
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      - pgdb
  pgdb:
    image: postgres
    container_name: pgdb
    environment:
      - POSTGRES_PASSWORD=ace1130
      - POSTGRES_USER=ace
      - POSTGRES_DB=personal_website
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
