# Generated by Django 3.1.2 on 2021-01-23 05:48

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogtag',
            options={'default_related_name': 'blog_tags'},
        ),
        migrations.AddField(
            model_name='blog',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='blog_covers'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blog_tags', to='blogs.blog'),
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blog_tags', to='blogs.tag'),
        ),
        migrations.AlterUniqueTogether(
            name='blogtag',
            unique_together={('blog', 'tag')},
        ),
    ]
