# Generated by Django 3.1.2 on 2021-01-23 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20210123_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtag',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_tags', to='blogs.blog'),
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_tags', to='blogs.tag'),
        ),
    ]
