apiVersion: v1
kind: Service
metadata:
  name: service-personal-website
  labels:
    app: personal-website
spec:
  type: LoadBalancer
  selector:
    app: personal-website
  ports:
    - port: 80
      targetPort: 80