# Generated by Django 3.0.5 on 2020-05-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='classification',
            field=models.CharField(choices=[('', '----'), ('company', 'Company'), ('freelance', 'Freelance'), ('personal', 'Personal')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
