# Generated by Django 3.0.5 on 2020-05-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio_images/'),
        ),
    ]
