# Generated by Django 3.1.2 on 2021-01-01 05:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20201015_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('positive_remarks', models.TextField()),
                ('improvement_remarks', models.TextField(verbose_name='Remarks on what needs to be improve')),
                ('email', models.EmailField(max_length=254)),
                ('platform', models.CharField(max_length=60)),
                ('project_description', models.CharField(max_length=75)),
                ('project_year', models.IntegerField(blank=True, null=True)),
                ('hash_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_answered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
