# Generated by Django 3.1.2 on 2021-01-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='improvement_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks on what needs to be improve'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='positive_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
