# Generated by Django 3.1.2 on 2021-01-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20210101_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
