# Generated by Django 3.1.2 on 2021-01-23 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_testimonial_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobexperience',
            old_name='task',
            new_name='tasks',
        ),
    ]
