# Generated by Django 3.1.2 on 2021-01-23 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_task_to_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobexperiencetask',
            name='job_experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.jobexperience'),
        ),
        migrations.AlterField(
            model_name='jobexperiencetask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.task'),
        ),
    ]
