# Generated by Django 3.0.5 on 2020-05-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_portfolio_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='back_end',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='front_end',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
