# Generated by Django 3.1.2 on 2020-10-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20201014_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['ordering'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterField(
            model_name='projects',
            name='back_end',
            field=models.CharField(max_length=255, verbose_name='Back-End Technology'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='front_end',
            field=models.CharField(max_length=255, verbose_name='Front-End Technology'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='ordering',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
