# Generated by Django 3.1.2 on 2020-10-14 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_auto_20201014_1508'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['ordering']},
        ),
    ]
