# Generated by Django 3.1.2 on 2020-10-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_auto_20201014_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='classification',
            field=models.CharField(choices=[('company', 'Company'), ('freelance', 'Freelance'), ('personal', 'Personal')], max_length=30),
        ),
    ]
