# Generated by Django 3.1.2 on 2020-10-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_auto_20201014_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobexperience',
            options={'ordering': ['ordering']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['ordering']},
        ),
        migrations.AddField(
            model_name='jobexperience',
            name='ordering',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='ordering',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
