# Generated by Django 3.1.2 on 2020-10-14 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_auto_20201014_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobexperience',
            old_name='job_name',
            new_name='company',
        ),
    ]
