# Generated by Django 3.1.2 on 2020-10-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_auto_20201014_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobexperience',
            name='ordering',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='ordering',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
