# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Set env and run python manage.py test
      run: |
        python manage.py test
      env:
        SECRET_KEY: '&5shu3839w7atvxn&a5fp#*nshh+6f(4aai+51@v0p0h3^l1-1'
        DEBUG: True
        EMAIL_HOST_USER: test@domain.com
        EMAIL_HOST_PASSWORD: t3st1234
        EMAIL_ADMIN: test_admin@test.com
        
